services:
  bmde-linux:
    image: aleixmt/bmde-linux:latest
    container_name: bmde-linux
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/input
    entrypoint: sh -c "cd /input && make clean && make"

