services:
  bmde-linux:
    image: aleixmt/bmde-linux:latest
    #build: .
    volumes:
     - ./:/input/  # Makefile in the same directory as compose, binary the same way as root folder of this project
     #- ../:/input/